# container and image variables
working_container: 'tmp/dev-wrk'
running_container: 'jo.lab' #changeme


start_script_dest: "~/bin/dev-env"
prompt: ""
base_version: "latest"
base_image: "registry.fedoraproject.org/fedora:{{ base_version }}"
#base_image: "centos/centos:7"

image_name: "jo.dev.f{{ base_version }}" #changeme
image_tag: latest

#base_image: "{{ image_name }}:{{ image_tag }}"

container_user: jeff
container_user_pass: ""

exec_opts:
- "--env COLORTERM=$COLORTERM"
- "--env DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
#- "$set_dbus_system_bus_address"
- "--env DESKTOP_SESSION=$DESKTOP_SESSION"
- "--env DISPLAY=$DISPLAY"
- "--env LANG=$LANG"
- "--env PS1=$PS1"
- "--env SHELL=$SHELL"
- "--env SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
- "--env TERM=$TERM"
- "--env VTE_VERSION=$VTE_VERSION"
- "--env XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP"
- "--env XDG_DATA_DIRS=$XDG_DATA_DIRS"
- "--env XDG_MENU_PREFIX=$XDG_MENU_PREFIX"
- "--env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
- "--env XDG_SEAT=$XDG_SEAT"
- "--env XDG_SESSION_DESKTOP=$XDG_SESSION_DESKTOP"
- "--env XDG_SESSION_ID=$XDG_SESSION_ID"
- "--env XDG_SESSION_TYPE=$XDG_SESSION_TYPE"
- "--env XDG_VTNR=$XDG_VTNR"
- "--tty"
- "--interactive"

create_opts:
- "--group-add wheel"
- "--hostname {{ running_container }}"
- "--interactive"
- "--name {{ running_container }}"
- "--network host"
#- "--privileged"
#- "--security-opt label=disable"
- "--tmpfs /dev/shm:size=$tmpfs_size"
- "--tty"
#- "--uidmap $UID:0:1"
#- "--uidmap 0:1:$UID"
#- "--uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid"
- "--volume $HOME:$HOME"
- "--volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
#- "--volume $dbus_system_bus_path:$dbus_system_bus_path"
- "--volume /dev/dri:/dev/dri"


# things to install
installs:
- name: golang
  state: latest
- name: java-openjdk
  state: latest
# - name: java-10-openjdk
#   state: latest
- name: java-11-openjdk
  state: latest
- name: code
  state: latest
- name: make
  state: latest
- name: cmake
  state: latest
# - name: g++
#   state: latest
- name: gcc
  state: latest
- name: libX11-xcb
  state: latest
- name: which
  state: latest
